name: Publish to npmjs.com and GitHub Packages

on:
  push:
    branches:
      - release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the release branch
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the package
      - name: Build
        run: npm run build

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: |
          echo "@moekyawsoe:registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PUB_TOKEN }}" >> .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUB_TOKEN }}

      # Publish to npmjs.com
      - name: Publish to npmjs.com
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}